import { FavoritePokemons } from "@/pokemons";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Favorites',
  description: 'Generated by store',
}
 
export default async function PokemonsPage() {
  return (
    <div className="p-4 flex flex-col">
      <h1 className="text-5xl my-2">Pokemon Favoritos <small className="text-blue-300">global state</small></h1>
      <FavoritePokemons />
    </div>
  );
}